<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Type' => 'Тип',
    'From' => 'Початковий рахунок',
    'To' => 'Рахунок призначення',
    'Amount From' => 'Надіслана сума',
    'Amount To' => 'Отримана сума',
    'Category' => 'Категорія',
    'Counterparty' =>  'Контрагент',
    'File' =>  'Файл',
    'Users' => 'Користувачі',
    'Currencies' => 'Валюти',
    'Categories' => 'Категорії',
    'Transactions' => 'Транзакції',
    'Counterparties' => 'Контрагенти',
    'Logout' => 'Вихід',
    'Create User' => 'Додати користувача',
    'Create Transaction' => 'Додати транзакцію',
    'Update' => 'Змінити',
    'Delete' => 'Видалити',
    'Update Transaction: ' => 'Змінити транзакцію: ',
    'Save' => 'Зберегти',
    'Username' => "Ім'я",
    'Password' => 'Пароль',
    'Email' => 'Електронна пошта',
    'Created At' => 'Створено',
    'Updated At' => 'Змінено',
    'Name' => 'Назва',
    'Default' => 'Основна',
    'Value' => 'Курс відносно основної',
    'Create Currency' => 'Додати валюту',
    'Update Currency: ' => 'Змінити валюту: ',
    'Update Category: ' => 'Змінити категорію: ',
    'Create Counterparty' => 'Додати котрагента',
    'Update Counterparty: ' => 'Змінити контрагента: ',
    'Transfer' => 'Переказ',
    'Expense' => 'Витрата',
    'Income' => 'Дохід',
    'All' => 'Усі',
    'Main' => 'Головна',
    'Accounts' => 'Акаунти',
    'Create Account' => 'Додати акаунт',
    'Amount' => 'Сума',
    'Id Currency' => 'Валюта',
    'Update Account: ' => 'Змінити акаунт: ',
    'Select account' => 'Обрати акаунт',
    'Select category' => 'Обрати категорію',
    'Select counterparty' => 'Обрати контрагента',
    'Yes' => 'Так',
    'No' => 'Ні',
    'Initial amount' => 'Початкова сума',
    'Current amount' => 'Поточна сума',
    'Show all transactions' => 'Перейти до всіх траназкцій',
    'Category statistics' => 'Статистика категорій',
    'Select date' => 'Виберіть дату',
    'Create Category' => 'Додати категорію',
    'Show statistics' => 'Показати статистику',
    'Cannot create chart, loaded general statistics' => 'Не вдалося стврити графік, завантажено загальний',
    'Create Counterparty' => 'Додати контрагента',
    'Expenses' => 'Витрати',
    'Incomes' => 'Доходи',
    'From date' => 'Від',
    'To date' => 'До',
    'Update currency rates' => 'Оновити курси валют',
];
